services:
  app:
    image: yiisoftware/yii2-php:8.3-fpm-24.3.0-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    networks:
      - net
    container_name: app
    
networks:
  net:
    driver: bridge